name: impromptu_generator2
description: A flutter application built to practice impromtpu speeches following the NSDA format.
authors: Rohin Inani
version: 1.2.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  circular_countdown_timer: ^0.2.0
  auto_size_text: ^2.1.0
  http: ^0.12.2
  url_launcher: ^6.0.2
  speech_to_text: ^2.3.0
  highlight_text: ^0.7.2
  avatar_glow: ^1.2.0
  share: ^0.6.5+2
  wakelock: ^0.2.1+1
  shared_preferences: ^0.5.12
  #  flutter_launcher_icons: ^0.7.5
  #  flutter_launcher_name:
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  image_path_android: "assets/icon.png"
  image_path_ios: "assets/logo_ios.png"
  ios: true

flutter_launcher_name:
  name: "Impromptu Generator"

flutter:
  uses-material-design: true
  assets:
    - assets/